### ISSUE TITLE
How to use this code with my wordpress woocommerce data

### ISSUE THREAD

**Issue by axhx** [Reshav-Paul/grodudes_app#2]
I have an doubt that what and where are all the changes I have to make to use app with my woocommerce product datas??
Can you please guide me

**Comment by Reshav-Paul** [comment]
Everywhere that I have created a WooCommerceApi object replace the url with your url and also the consumer key and consumer secret. I put them in a dictionary in secrets.dart file and exported that file. How you do it is upto you. Once the urls, keys and secrets have been replaced everything else should work just fine.

Since this is not a valid issue I am closing this thread.

**Comment by axhx** [comment]
Then if I create secret.dart file with all my secret key and import that...
Application will work fine?
