### ISSUE TITLE
Not fetching products , nor categories and can't login for some reason

### ISSUE THREAD

**Issue by LebToki** [Reshav-Paul/grodudes_app#6]
Wonder why !
few bits and pieces need some code changes not sure if you are willing to revisit your code here

**Comment by Reshav-Paul** [comment]
You are right. I won't be able to revisit this. Have since moved on from flutter. If you provide some more information maybe I can help. Fetching products, categories and user login/sign-up is pretty much the bulk of what the app does.

**Comment by Reshav-Paul** [comment]
Have you found an issue? Else I might have to close this.

**Comment by Reshav-Paul** [comment]
Found this issue from #7 

See if this works - 

In main.dart file find the loadData() function. Inside it there is a section where I check if the site is in maintenance mode. Comment out that section or remove it because that was a custom implementation and won't work in your case.

You can find it in the first try...catch block. Remove it and see if it works.
